#------------------------------------------------------------------------------------#
# config for logging
#------------------------------------------------------------------------------------#
logging:
  log_path: '/Users/mmt10498/Desktop/Django/cricbett/booking_service/logs'
  log_file: 'cricbett-booking.log'
  log_format:
    "%(asctime)s %(levelname)s %(filename)s %(funcName)s [%(lineno)d]: %(message)s"